name: Docker Hub build

on:
  push:
    branches:
      - "develop"

jobs:
  dockerhub:
    uses: usdot-fhwa-stol/actions/.github/workflows/dockerhub.yml@main
    with:
      DOCKER_TAG: usdotfhwastoldev/${{ github.event.repository.name }}:${{ github.ref_name }}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}